In [56]:
import numpy as np

In [57]:
mu1 = np.array([0,1])
cov1 = np.array([[3,2],[2,3]])
n1 = 30000
x1 = np.random.multivariate_normal(mu1, cov1, size=n1, check_valid='warn', tol=1e-8)
mu1 = np.expand_dims(x1.mean(0),1)
cov1 = np.cov(x1.T)

mu2 = np.array([3,0])
cov2 = np.array([[0.3,0.2],[0.2,0.3]])
n2 = 30000
x2 = np.random.multivariate_normal(mu2, cov2, size=n2, check_valid='warn', tol=1e-8)
mu2 = np.expand_dims(x2.mean(0),1)
cov2 = np.cov(x2.T)


In [58]:
x = np.vstack((x1,x2))
mu_real = np.expand_dims(x.mean(0),1)
cov_real = np.cov(x.T)

In [59]:
n = n1+n2
mu_comp = (n1*mu1 + n2*mu2)/n

cov_comp = (n1**2*cov1 + n2**2*cov2 + (n1*mu1 + n2*mu2)@(n1*mu1+n2*mu2).T)/n**2 - mu_comp@mu_comp.T
cov_comp1 = (n1/n)**2*cov1 + (n2/n)**2*cov2
cov_comp2 = cov1@np.linalg.inv(cov1+cov2)@cov2

p1 = n1/n;p2=n2/n
cov_comp3 = n1*

In [60]:
print(mu_real - mu_comp)
print(cov_real - cov_comp)
print(cov_real-cov_comp2)

[[0.00000000e+00]
 [3.33066907e-16]]
[[ 3.06622921 -0.2101446 ]
 [-0.2101446   1.07601423]]
[[3.61304592 0.15691945]
 [0.15691945 1.62644441]]


In [54]:
cov1@np.linalg.inv(cov1+cov2)@cov2

array([[0.27297079, 0.18145889],
       [0.18145889, 0.27198893]])

In [55]:
cov_real

array([[3.89997602, 0.3525411 ],
       [0.3525411 , 1.90928943]])